# GitLeaks Configuration for Blog-App
title = "Blog-App Security Configuration"

[extend]
useDefault = true

[[rules]]
description = "AWS Access Key ID"
id = "aws-access-key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "AWS Secret Access Key"
id = "aws-secret-key"
regex = '''[A-Za-z0-9/+=]{40}'''
tags = ["secret", "AWS"]

[[rules]]
description = "Database Connection String"
id = "database-connection"
regex = '''(mongodb|mysql|postgresql|redis)://[^\s'"]*'''
tags = ["database", "connection"]

[[rules]]
description = "JWT Secret"
id = "jwt-secret"
regex = '''jwt[_-]?secret[_-]?key?\s*[:=]\s*['""]?[A-Za-z0-9+/]{32,}['""]?'''
tags = ["jwt", "secret"]

[[rules]]
description = "API Keys"
id = "api-key"
regex = '''api[_-]?key\s*[:=]\s*['""]?[A-Za-z0-9]{20,}['""]?'''
tags = ["api", "key"]

[allowlist]
description = "Allowlist for false positives"
paths = [
  '''.*\.md$''',
  '''.*\.txt$''',
  '''package-lock\.json$''',
  '''yarn\.lock$''',
  '''node_modules/.*''',
  '''tests?/.*''',
  '''__tests__/.*''',
  '''.*\.test\.js$''',
  '''.*\.spec\.js$'''
]

commits = [
  # Add specific commit hashes here if needed
]
