apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
    component: secrets
type: Opaque
data:
  {{- if .Values.secrets.mongodb.uri }}
  MONGO_URI: {{ .Values.secrets.mongodb.uri }}
  {{- end }}
  {{- if .Values.secrets.jwt.secret }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret }}
  {{- end }}
