apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.mongoUri }}
  mongoUri: {{ .Values.secrets.mongoUri | b64enc }}
  {{- else }}
  mongoUri: {{ "mongodb://localhost:27017/blogapp" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc }}
  {{- else }}
  jwtSecret: {{ "your-jwt-secret-key-change-in-production" | b64enc }}
  {{- end }}
