{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-app.fullname" . }}-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "blog-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
